### ISSUE TITLE
ihdp data indices

### ISSUE THREAD

**Issue by farazmah** [claudiashi57/dragonnet#14]
Hi,

Thanks for sharing your interesting work.  I am trying to work through some of the results of the paper  

I noticed that the column indices mentioned `idhp_data.py`:
```
 binfeats = [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
 contfeats = [i for i in range(25) if i not in binfeats]
```
They do not match the columns in the csv files contained in the `dat` folder. E.g. `ihdp_npci_1.csv`

Can you please advise if this is the correct reference files.

Thanks in advance.

**Comment by 00helloworld** [comment]
Hi, these lines are below the code you referenced:
`mu_0, mu_1, x = data[:, 3][:, None], data[:, 4][:, None], data[:, 5:]`
   ` perm = binfeats + contfeats`
    `x = x[:, perm]`
    `return x`
The result is `x` and `x = data[:, 5:]` so `x` has 25 columns. That just match `perm` where `perm = binfeats + contfeats`.
This is my opinion and hope it can help you.

**Comment by farazmah** [comment]
Hi,

My concern is that the `binfeat` indices don't correspond to the binary feature columns in the csv files provided.  For example column 6 (first index in `binfeat`) in the [ihdp_npci_1.csv ](https://github.com/claudiashi57/dragonnet/blob/master/dat/ihdp/csv/ihdp_npci_1.csv) is clearly a continuous feature.

Thanks

**Comment by farazmah** [comment]
Thanks for the reply
That clears it up.
