### ISSUE TITLE
Query about the IHDP data folder

### ISSUE THREAD

**Issue by gourxb** [claudiashi57/dragonnet#5]
According to the the original paper (Hill 2011) there are 747 units (139 treated, 608 control). In the dat folder there are 50 csv. 

Which is the original csv? 
Also, Why are there are 50 csv? Are they simulated?

**Comment by jameszhou-gl** [comment]
The author did 1000 replications of original data(747 observations including 139 treat and 608 control) and he uploaded 50 csv due to the limitation of Github. I'm also curious about the extra 950 csv files.

**Comment by claudiashi57** [comment]
please send me an email at claudia.j.shi@gmail.com I would happy to share the remaining simulated CSVs.
