### ISSUE TITLE
Demo notebook on simulated examples to check correctness of implementation?

### ISSUE THREAD

**Issue by gmgeorg** [claudiashi57/dragonnet#6]
Hi,

thanks for putting the code together! 

I tried to train dragonnet on toy examples ([KangSchafer](https://github.com/google/empirical_calibration/blob/master/notebooks/causal_inference_kang_schafer.ipynb)) with 0 treatment effect.  Various variations on hidden layers, batch sizes, etc yield estimates that are completely off (ATE = -60).  Did you test your implementation on toy examples from literature or your own simulated ground truth data to verify it works as intended?

Some example code

```
 np.random.seed(123)
import empirical_calibration as ec
simulation = ec.data.kang_schafer.Simulation(size=2000)

t = simulation.treatment.reshape(-1, 1)
x = simulation.transformed_covariates
y = simulation.outcome.reshape(-1, 1)
t.shape, x.shape, y.shape
```
```
# Use causalml to show other methods work as intended
def _ks_df(size, seed = None):
    if seed:
        np.random.seed(seed)
    simulation = ec.data.kang_schafer.Simulation(size=size)
    df = pd.DataFrame(
    np.column_stack([
        simulation.treatment, simulation.covariates,
        simulation.transformed_covariates, simulation.outcome
    ]))
    df.columns = [
    "treatment", "z1", "z2", "z3", "z4", "x1", "x2", "x3", "x4", "outcome"
    ]
    return df

df = _ks_df(size=1000)
from causalml.inference.meta import XGBTRegressor

xg = XGBTRegressor(random_state=42)
te, lb, ub = xg.estimate_ate(df[["x1", "x2", "x3", "x4"]], 
                             df["treatment"], df["outcome"])
print('Average Treatment Effect (XGBoost): {:.2f} ({:.2f}, {:.2f})'.format(te[0], lb[0], ub[0]))
```

When using dragonnet via the `acic_main` functions the estimates are entirely off essentially equal to the very naive method of taking outcome differences (--> ATE estimates of roughly -20).

```   
test_outputs, train_outputs = acic_main.train_and_predict_dragons(t, y, x,
                                    targeted_regularization=True,
                                    output_dir="",
                                                                  dragon="dragonnet",
                                    knob_loss=models.dragonnet_loss_binarycross,
                                                              ratio=1.,
                                    val_split=0.2, batch_size=64, hidden_size_multiplier=2, verbose=False)

```
Doing this 10 times for sample size of n=5000 the ATE estimates (by method) are as follows:
![image](https://user-images.githubusercontent.com/48655643/107731256-80303e80-6cc3-11eb-9a09-7b39b898a635.png)

Similarly for `targeted_regularization=False`.  Do you have notebooks/documentation on running this on such toy examples for verification of implementation?

**Comment by claudiashi57** [comment]
yes, all our experiments are semi-synthetic, i.e., with ground truth. 
acic_main.train_and_predict_dragons is specific to the ACIC data frame. Have you checked whether you are feeding the data correctly?
