### ISSUE TITLE
Query about NPCI data

### ISSUE THREAD

**Issue by cgueret** [claudiashi57/dragonnet#7]
Could you please explain how you used NPCI to generate the 1k data files mentioned in the paper?
I tried to ask the author and he suggested getting back to you: https://github.com/vdorie/npci/issues/2
This files would be useful to me to replicate your results and compare them to our own approach

**Comment by jameszhou-gl** [comment]
Hi, cgueret. I'm also curious about the 1k data. Do you get this files?

**Comment by claudiashi57** [comment]
please send me an email at claudia.j.shi@gmail.com I would happy to share the remaining simulated CSVs.
