### ISSUE TITLE
Correct test_size  in train_test_split of ihdp_main.py to reproduce in-sample and out-sample paper results 

### ISSUE THREAD

**Issue by gtesei** [claudiashi57/dragonnet#8]
**From documentation:** 
_Note: the default code use all the data for prediction and estimation. If you want to get the in-sample or out-sample error: i) change the `train_test_split` criteria in `ihdp_main.py`; ii) rerun the neural net training; iii) run `ihdp_ate.py` with apporiate in-sample data and out-sample data._ 

**From paper:** 
_We randomly split the data into **test/validation/train** with proportion **63/27/10** and report the in sample and out of sample estimation errors._

**Is this split correct (train size 10% vs. test size 63%)?**

**Comment by claudiashi57** [comment]
ahh sorry --- that's a typo. it's train 63%; test 10%

**Comment by gtesei** [comment]
Thanks for the answer. I applied train/validation/test with proportion 63/27/10 in `experiment/ihdp_main.py`:
```
def train_and_predict_dragons(t, y_unscaled, x, targeted_regularization=True, output_dir='',
                              knob_loss=dragonnet_loss_binarycross, ratio=1., dragon='', val_split=0.3, batch_size=64):
    ...
    np.random.seed(i)
    train_index, test_index = train_test_split(np.arange(x.shape[0]), test_size=0.1, random_state=1)
```
Also, I modified `src/process_result/ihdp_ate.py` to produce test results: 

```
def main():
    print("************ TRAIN *********************")
    dict, tmle_dict = make_table(train_test='train')
    print("The back door adjustment result is below")
    print(dict)

    print("the tmle estimator result is this ")
    print(tmle_dict)


    print("************ TEST *********************")
    dict, tmle_dict = make_table(train_test='test')
    print("The back door adjustment result is below")
    print(dict)

    print("the tmle estimator result is this ")
    print(tmle_dict)
```
I was able to reproduce the training result, i.e. 'targeted_regularization': 0.14565543186980867, but for the heldout I got 'targeted_regularization': 0.26716736650641765 instead of ~0.20 as reported in the paper. Any idea?

**Comment by claudiashi57** [comment]
Hi, are you running on the 50 IHDP csv on github? The result in the paper is over 1000 IHDP csvs. I only uploaded a subset because of github space constraint. if you want all the csv files, you can send me an email at claudia.j.shi@gmail.com
